import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/base/navbar'
import Footer from '@/components/base/footer/footer.jsx'
import ContactUs from '@/components/base/contactUs/contactUs'
import UpComingEvent from '@/components/base/upComingEvent'
import ContactPopUpBtn from '@/components/base/contactPopUpBtn'
import ShowEvent from '@/components/base/showEvent'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} scrollbar`}>
        <ShowEvent />
        <ContactPopUpBtn />
        <UpComingEvent />
        <Navbar />
        {children}
        <ContactUs />
        <Footer />
      </body>
    </html>
  )
}
