import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/base/navbar'
import Footer from '@/components/base/footer/footer.jsx'
import ContactUs from '@/components/base/contactUs/contactUs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <ContactUs />
        <Footer />
        </body>
    </html>
  )
}
